#!/usr/bin/env tsx
/**
 * scripts/sign-demo-pfp-upload.ts — end-to-end proof for Task 4's signed
 * PFP/name upload, without a real browser wallet: signs the exact same
 * message web/components/CustomizeForm.tsx builds (web/lib/signedUpload.ts
 * is the single shared source of truth for that format) using the demo
 * agent's own keypair (DEMO_PROVIDER_KEYPAIR — the same registered agent
 * the RUN DEMO button drives), then POSTs it to a running dev server's
 * /api/pfp route exactly like the browser form does.
 *
 * Also proves the negative case: a tampered signature must be rejected.
 *
 * Usage: npx tsx --env-file=web/.env.local scripts/sign-demo-pfp-upload.ts [siteUrl]
 * Requires: a `next start`/`next dev` server already running at siteUrl
 * (default http://localhost:3000), and DEMO_PROVIDER_KEYPAIR set (from
 * web/.env.local, generated by scripts/setup-demo-agent.ts).
 */

import { Keypair } from "@solana/web3.js";
import nacl from "tweetnacl";
import sharp from "sharp";
import { buildSignedMessage, sha256Hex } from "../web/lib/signedUpload";

// A real, non-square (64x40) synthesized PNG — exercises the server's
// actual sharp-based validation path (format sniff, decode, center-crop to
// square, re-encode to strip metadata) against genuine image content,
// rather than a degenerate 1x1 edge case.
async function makeTestPng(): Promise<Buffer> {
  return sharp({ create: { width: 64, height: 40, channels: 3, background: { r: 224, g: 161, b: 0 } } })
    .png()
    .toBuffer();
}

function loadDemoKeypair(): Keypair {
  const raw = process.env.DEMO_PROVIDER_KEYPAIR;
  if (!raw) throw new Error("DEMO_PROVIDER_KEYPAIR is not set — run with --env-file=web/.env.local");
  return Keypair.fromSecretKey(Uint8Array.from(JSON.parse(raw)));
}

async function postUpload(
  siteUrl: string,
  opts: { agentPubkey: string; timestampMs: number; displayName: string; signature: Uint8Array; imageBytes: Buffer }
): Promise<{ status: number; body: unknown }> {
  const form = new FormData();
  form.set("agentPubkey", opts.agentPubkey);
  form.set("timestampMs", String(opts.timestampMs));
  form.set("displayName", opts.displayName);
  form.set("signature", Buffer.from(opts.signature).toString("base64"));
  form.set("file", new Blob([new Uint8Array(opts.imageBytes)], { type: "image/png" }), "pfp.png");

  const res = await fetch(`${siteUrl}/api/pfp`, { method: "POST", body: form });
  return { status: res.status, body: await res.json().catch(() => null) };
}

async function main() {
  const siteUrl = process.argv[2] ?? "http://localhost:3000";
  const kp = loadDemoKeypair();
  const agentPubkey = kp.publicKey.toBase58();
  const imageBytes = await makeTestPng();
  const displayName = "demo-signed";

  console.log(`Agent (demo provider): ${agentPubkey}`);
  console.log(`Target: ${siteUrl}/api/pfp`);

  // ── 1. Legitimate signed upload ──────────────────────────────────────────
  const timestampMs = Date.now();
  const payloadHashHex = await sha256Hex(new Uint8Array(imageBytes));
  const message = buildSignedMessage({ agentPubkey, timestampMs, displayName, payloadHashHex });
  const signature = nacl.sign.detached(new TextEncoder().encode(message), kp.secretKey);

  const good = await postUpload(siteUrl, { agentPubkey, timestampMs, displayName, signature, imageBytes });
  console.log("\n[1] Legitimate signed upload ->", good.status, good.body);
  if (good.status !== 200 || !(good.body as { ok?: boolean })?.ok) {
    throw new Error("expected the legitimately signed upload to succeed");
  }

  // ── 2. Tampered signature must be rejected ──────────────────────────────
  const tampered = new Uint8Array(signature);
  tampered[0] ^= 0xff; // flip a byte — same message, same timestamp, corrupted signature
  const bad = await postUpload(siteUrl, {
    agentPubkey,
    timestampMs,
    displayName,
    signature: tampered,
    imageBytes,
  });
  console.log("\n[2] Tampered signature ->", bad.status, bad.body);
  if (bad.status === 200 && (bad.body as { ok?: boolean })?.ok) {
    throw new Error("SECURITY ISSUE: a tampered signature was accepted");
  }

  console.log("\nAll checks passed: legitimate upload accepted, tampered signature rejected.");
}

main().catch((err) => {
  console.error("FAILED:", err instanceof Error ? err.message : err);
  process.exit(1);
});
